#!/bin/bash

##################################################
# Settings

readonly border_width=2
readonly border_color_focused=0x93a1a1
readonly border_color_unfocused=0x38464b
readonly border_color_urgent=0xffcb6b

systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

riverctl default-attach-mode below
riverctl focus-follows-cursor normal
riverctl set-cursor-warp on-output-change

riverctl border-width $border_width
riverctl background-color 0x121212
riverctl border-color-focused $border_color_focused
riverctl border-color-unfocused $border_color_unfocused
riverctl border-color-urgent $border_color_urgent
riverctl xcursor-theme Breeze_Light 32

riverctl set-repeat 50 300

#riverctl keyboard-layout -model 'us(altgr-intl)' -options 'caps:ctrl_modifier' 'us(altgr-intl)'
#riverctl keyboard-layout -model 'us(altgr-intl)' -options 'caps:super' 'us(altgr-intl)'
riverctl keyboard-layout -model 'us(altgr-intl)' -options 'compose:caps' 'us(altgr-intl)'

riverctl input '*Touchpad' tap enabled
riverctl input '*Touchpad' drag-lock enabled
riverctl input '*G403*' accel-profile flat
riverctl input '*Glorious*' accel-profile flat

riverctl map normal Super+Shift Delete exit
riverctl map normal Super Delete spawn 'loginctl lock-session'

riverctl rule-add -app-id 'float*' float
riverctl rule-add -app-id 'qalculate*' float
riverctl rule-add -app-id 'thunderbird' tags $((1 << 6))
riverctl rule-add -app-id 'discord' tags $((1 << 7))
riverctl rule-add -app-id 'ferdium' tags $((1 << 8))

##################################################
# Window Management

riverctl map normal Super Q close
riverctl map normal Super M zoom
riverctl map normal Super F toggle-fullscreen
riverctl map normal Super Space toggle-fullscreen

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super H focus-view left
riverctl map normal Super L focus-view right

riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous
riverctl map normal Super+Shift H swap left
riverctl map normal Super+Shift L swap right

riverctl map normal Super O focus-output next
riverctl map normal Super I focus-output previous

riverctl map normal Super+Shift O send-to-output next
riverctl map normal Super+Shift I send-to-output previous

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

riverctl map normal Super T toggle-float
riverctl map normal Super+Shift Up snap up 
riverctl map normal Super+Shift Down snap down 
riverctl map normal Super+Shift Left snap left 
riverctl map normal Super+Shift Right snap right 

if [[ -f /usr/bin/wideriver ]]; then
	riverctl map normal Super Bracketleft send-layout-cmd wideriver "--ratio -0.05"
	riverctl map normal Super Bracketright send-layout-cmd wideriver "--ratio +0.05"

	riverctl map normal Super+Shift Bracketleft send-layout-cmd wideriver "--count +1"
	riverctl map normal Super+Shift Bracketright send-layout-cmd wideriver "--count -1"

	riverctl map normal Super N send-layout-cmd wideriver "--layout left"
	riverctl map normal Super Space send-layout-cmd wideriver "--layout monocle"
	riverctl map normal Super+Shift N send-layout-cmd wideriver "--layout wide"

	riverctl map normal Super Up    send-layout-cmd wideriver "--layout top"
	riverctl map normal Super Down  send-layout-cmd wideriver "--layout bottom"
	riverctl map normal Super Left  send-layout-cmd wideriver "--layout left"
	riverctl map normal Super Right send-layout-cmd wideriver "--layout right"

	riverctl map normal Super Slash send-layout-cmd wideriver "--stack diminish"
	riverctl map normal Super+Shift Slash send-layout-cmd wideriver "--stack even"

	riverctl default-layout wideriver
	wideriver \
		--stack diminish \
		--ratio 0.6 \
		--smart-gaps \
		--border-width-monocle 0 \
		--border-width $border_width \
		--border-width-smart-gaps 0 \
		--border-color-focused $border_color_focused \
		--border-color-unfocused $border_color_unfocused &
else
	riverctl map normal Super Bracketleft send-layout-cmd rivertile "main-ratio -0.05"
	riverctl map normal Super Bracketright send-layout-cmd rivertile "main-ratio +0.05"

	riverctl map normal Super+Shift Bracketleft send-layout-cmd rivertile "main-count +1"
	riverctl map normal Super+Shift Bracketright send-layout-cmd rivertile "main-count -1"

	riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
	riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
	riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
	riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

	riverctl default-layout rivertile
	rivertile -view-padding 4 -outer-padding 0 &
fi

riverctl map normal Super Tab focus-previous-tags

all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

for i in {1..9}; do
	tags=$((1 << ($i - 1)))
	riverctl map normal Super $i set-focused-tags $tags
	riverctl map normal Super+Shift $i set-view-tags $tags
	riverctl map normal Super+Control $i toggle-focused-tags $tags
	riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

##################################################
# Applications

riverctl map normal Super Return spawn 'alacritty'
riverctl map normal Super R spawn 'bemenu-run'
riverctl map normal Super+Shift R spawn 'bemenu-run-term'
riverctl map normal Super E spawn 'doublecmd'
riverctl map normal Super C spawn 'qalculate-gtk'
#riverctl map normal Super Backslash spawn 'fsearch --new-window'
riverctl map normal Super Backslash spawn 'bemenu-file'
riverctl map normal Super+Shift Backslash spawn 'bemenu-file /'
riverctl map normal Super U spawn 'dunstctl close'
riverctl map normal Super+Shift U spawn 'dunstctl history-pop'
riverctl map normal Super Y spawn 'dunstctl context'
riverctl map normal Super Period spawn 'bemoji --type --clip --noline'

riverctl map normal None Print spawn 'fnkey screenshot'
riverctl map normal Super S spawn 'fnkey screenshot-region'
riverctl map normal Super+Shift S spawn 'fnkey screenshot-editor'

for mode in normal locked; do
	riverctl map $mode Super F9 spawn 'fnkey screen-on'

	riverctl map $mode None XF86AudioRaiseVolume  spawn 'fnkey volume-up'
	riverctl map $mode None XF86AudioLowerVolume  spawn 'fnkey volume-down'
	riverctl map $mode None XF86AudioMute         spawn 'fnkey volume-mute'
	riverctl map $mode None XF86AudioMedia        spawn 'fnkey media'
	riverctl map $mode None XF86AudioPlay         spawn 'fnkey media-play'
	riverctl map $mode None XF86AudioPrev         spawn 'fnkey media-previous'
	riverctl map $mode None XF86AudioNext         spawn 'fnkey media-next'
	riverctl map $mode None XF86MonBrightnessUp   spawn 'fnkey brightness-up'
	riverctl map $mode None XF86MonBrightnessDown spawn 'fnkey brightness-down'
done

##################################################
# Autostart

swaybg --image ~/Pictures/Wallpapers/wallpaper --mode fill &

waybar &
dunst &
nm-applet &
wl-clip-persist --clipboard both &
#blueman-applet &

swayidle -w \
	lock 'ssh-add -D' \
	lock swaylock \
	before-sleep 'ssh-add -D' \
	before-sleep swaylock &

#wlr-randr --output eDP-1 --scale 1.5 &
